### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [analytics-engineers/gtm-server-variable-substring#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) The home page [url](https://www.analytics-engineers.com/) mentioned in the metadata file is not valid. We see "This site can’t be reached" error. Please provide valid url.
![Screenshot 2021-09-27 2 18 10 PM](https://user-images.githubusercontent.com/53495700/134986905-d9576e24-bac6-42e9-86f7-287a6fdd5168.png)

**Comment by madstegge** [comment]
@praveena-pappu > This issue has been resolved.
